---
driver:
  name: vagrant
  vm_hostname: spree.myspreeshop.com
  driver_config:
  network:
  - ["private_network", {ip: "33.33.33.10"}]
  customize:
      cpus: 2
      memory: 1024

provisioner:
  name: chef_solo

platforms:
  - name: centos-6.4

suites:
  - name: spree_vm
    run_list:
     - recipe[spree::default]
     - recipe[rvm::vagrant]
    attributes:
      resolvconf:
      nameserver: '8.8.8.8'
